// WorkSync 목업 데이터

export const AVATARS = {
  ceo: "https://images.unsplash.com/photo-1720805752653-10ddccea4c94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
  manager: "https://images.unsplash.com/photo-1651684215020-f7a5b6610f23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
  seniorDev: "https://images.unsplash.com/photo-1758600587811-e9a20851cf7d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
  developer: "https://images.unsplash.com/photo-1758876204244-930299843f07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
  designer: "https://images.unsplash.com/photo-1689600944138-da3b150d9cb8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
};

export const TEAM_MEMBERS = [
  { id: 1, name: "James Whitmore", role: "대표이사", dept: "경영진", avatar: AVATARS.ceo, email: "j.whitmore@worksync.io", status: "online" },
  { id: 2, name: "Ryan Chen", role: "프로젝트 매니저", dept: "제품팀", avatar: AVATARS.manager, email: "r.chen@worksync.io", status: "online" },
  { id: 3, name: "Aisha Park", role: "시니어 개발자", dept: "개발팀", avatar: AVATARS.seniorDev, email: "a.park@worksync.io", status: "away" },
  { id: 4, name: "Marcus Lee", role: "프론트엔드 개발자", dept: "개발팀", avatar: AVATARS.developer, email: "m.lee@worksync.io", status: "online" },
  { id: 5, name: "Sofia Nguyen", role: "UI/UX 디자이너", dept: "디자인팀", avatar: AVATARS.designer, email: "s.nguyen@worksync.io", status: "offline" },
];

export const APPROVAL_DOCS = [
  { id: "APV-2024-0891", title: "3분기 예산 요청 - 마케팅 부서", type: "예산", status: "pending", requester: TEAM_MEMBERS[1], date: "2024-07-10", priority: "high", approvers: [TEAM_MEMBERS[0], TEAM_MEMBERS[1]] },
  { id: "APV-2024-0890", title: "재택근무 정책 개정안 2024", type: "인사 정책", status: "approved", requester: TEAM_MEMBERS[0], date: "2024-07-09", priority: "medium", approvers: [TEAM_MEMBERS[0]] },
  { id: "APV-2024-0889", title: "클라우드 인프라 업그레이드 제안", type: "IT 요청", status: "pending", requester: TEAM_MEMBERS[2], date: "2024-07-08", priority: "high", approvers: [TEAM_MEMBERS[0], TEAM_MEMBERS[1], TEAM_MEMBERS[2]] },
  { id: "APV-2024-0888", title: "새 디자인 시스템 라이선스 구매", type: "구매", status: "rejected", requester: TEAM_MEMBERS[4], date: "2024-07-07", priority: "low", approvers: [TEAM_MEMBERS[1]] },
  { id: "APV-2024-0887", title: "팀 워크숍 기획 - 2024년 9월", type: "행사", status: "approved", requester: TEAM_MEMBERS[3], date: "2024-07-05", priority: "medium", approvers: [TEAM_MEMBERS[0], TEAM_MEMBERS[1]] },
  { id: "APV-2024-0886", title: "초과 근무 승인 - 7월 스프린트", type: "인사", status: "pending", requester: TEAM_MEMBERS[2], date: "2024-07-04", priority: "medium", approvers: [TEAM_MEMBERS[0]] },
  { id: "APV-2024-0885", title: "법인 구입비 법인카드 지출결의서 - 마케팅 부서", type: "구매", status: "pending", requester: TEAM_MEMBERS[1], date: "2024-07-10", priority: "high", approvers: [TEAM_MEMBERS[0], TEAM_MEMBERS[1]] },
  { id: "APV-2024-0884", title: "팀 워크숍 기획 - 7월 스프린트", type: "행사", status: "approved", requester: TEAM_MEMBERS[2], date: "2024-07-09", priority: "medium", approvers: [TEAM_MEMBERS[0]] },
  { id: "APV-2024-0883", title: "초과 근무 승인 - 2024년 9월", type: "인사", status: "pending", requester: TEAM_MEMBERS[4], date: "2024-07-08", priority: "high", approvers: [TEAM_MEMBERS[0], TEAM_MEMBERS[1], TEAM_MEMBERS[2]] },
  { id: "APV-2024-0882", title: "결재 문서 제목", type: "구매", status: "pending", requester: TEAM_MEMBERS[4], date: "2024-07-08", priority: "high", approvers: [TEAM_MEMBERS[0]] },
];

export const KANBAN_TASKS = {
  todo: [
    { id: "T-101", title: "WorkSync 2.0 온보딩 플로우 디자인", priority: "high", assignee: TEAM_MEMBERS[4], due: "7월 18일", tags: ["Design", "UX"], progress: 0, startDate: "2026-05-28", endDate: "2026-06-28" },
    { id: "T-102", title: "API 문서 업데이트", priority: "medium", assignee: TEAM_MEMBERS[2], due: "7월 22일", tags: ["Docs", "Backend"], progress: 0, startDate: "2026-05-20", endDate: "2026-06-15" },
    { id: "T-103", title: "스테이징 CI/CD 파이프라인 설정", priority: "high", assignee: TEAM_MEMBERS[3], due: "7월 20일", tags: ["DevOps"], progress: 0, startDate: "2026-05-15", endDate: "2026-06-10" },
  ],
  inProgress: [
    { id: "T-098", title: "알림 서비스 구현", priority: "high", assignee: TEAM_MEMBERS[2], due: "7월 15일", tags: ["Backend", "API"], progress: 65, startDate: "2026-05-10", endDate: "2026-06-25" },
    { id: "T-099", title: "대시보드 위젯 재디자인", priority: "medium", assignee: TEAM_MEMBERS[4], due: "7월 17일", tags: ["Design"], progress: 40, startDate: "2026-05-12", endDate: "2026-06-18" },
    { id: "T-100", title: "인증 토큰 만료 버그 수정", priority: "urgent", assignee: TEAM_MEMBERS[3], due: "7월 12일", tags: ["Bug", "Security"], progress: 80, startDate: "2026-05-05", endDate: "2026-06-05" },
  ],
  review: [
    { id: "T-095", title: "메신저 읽음 확인 기능", priority: "medium", assignee: TEAM_MEMBERS[3], due: "7월 11일", tags: ["Frontend", "Feature"], progress: 90, startDate: "2026-05-08", endDate: "2026-06-08" },
    { id: "T-096", title: "결재선 컴포넌트 v2", priority: "high", assignee: TEAM_MEMBERS[4], due: "7월 10일", tags: ["Component"], progress: 85, startDate: "2026-05-01", endDate: "2026-06-01" },
  ],
  done: [
    { id: "T-091", title: "사용자 프로필 설정 페이지", priority: "medium", assignee: TEAM_MEMBERS[2], due: "7월 08일", tags: ["Frontend"], progress: 100, startDate: "2026-04-20", endDate: "2026-05-28" },
    { id: "T-092", title: "Okta SSO 연동", priority: "high", assignee: TEAM_MEMBERS[2], due: "7월 05일", tags: ["Security", "Integration"], progress: 100, startDate: "2026-04-15", endDate: "2026-05-25" },
    { id: "T-093", title: "엑셀 내보내기 기능", priority: "low", assignee: TEAM_MEMBERS[3], due: "7월 01일", tags: ["Feature"], progress: 100, startDate: "2026-04-10", endDate: "2026-05-20" },
  ],
};

export const MESSAGES = [
  { id: 1, sender: TEAM_MEMBERS[1], content: "안녕, 최신 디자인 목업 확인해줄 수 있어? 공유 드라이브에 올려놨어.", time: "오전 10:32", isMine: false },
  { id: 2, sender: TEAM_MEMBERS[3], content: "지금 보고 있어. 색상 팔레트 정말 좋다 👌", time: "오전 10:35", isMine: true },
  { id: 3, sender: TEAM_MEMBERS[1], content: "고마워! Sofia가 정말 열심히 작업했어. 새 온보딩 모달도 생각 중이야.", time: "오전 10:38", isMine: false },
  { id: 4, sender: TEAM_MEMBERS[3], content: "맞아. 오늘 오후에 리뷰 콜 잡을까?", time: "오전 10:38", isMine: true },
  { id: 5, sender: TEAM_MEMBERS[1], content: "응, 오후 3시로 하자. 지금 캘린더 초대 보낼게.", time: "오전 10:39", isMine: false },
  { id: 6, sender: TEAM_MEMBERS[3], content: "완벽해. Aisha도 포함시킬게. 백엔드 연동 담당이니까.", time: "오전 10:40", isMine: true },
  { id: 7, sender: TEAM_MEMBERS[1], content: "좋아. 그리고 Q3 예산 문서 오늘 퇴근 전까지 결재해야 돼.", time: "오전 10:42", isMine: false },
  { id: 8, sender: TEAM_MEMBERS[3], content: "알겠어! 점심 전에 검토하고 결재할게.", time: "오전 10:43", isMine: true },
];

export const RECENT_POSTS = [
  { id: 1, author: TEAM_MEMBERS[0], content: "🎉 2분기 결과가 나왔습니다 — 목표를 12% 초과 달성했어요! 모두 수고하셨습니다. 전체 보고서는 공유 드라이브에 있습니다.", time: "1시간 전", likes: 8, comments: 3 },
  { id: 2, author: TEAM_MEMBERS[1], content: "알림: 오늘 오후 4시 회의실 B에서 스프린트 회고가 있습니다. 업무 현황을 준비해 주세요.", time: "3시간 전", likes: 4, comments: 1 },
  { id: 3, author: TEAM_MEMBERS[4], content: "🎨 새 디자인 시스템 문서가 공개되었습니다! Wiki에서 업데이트된 컴포넌트와 토큰을 확인해 보세요.", time: "5시간 전", likes: 12, comments: 6 },
];

export const BOARD_CATEGORIES = [
  { id: "all", label: "전체 게시판", path: "/board" },
  { id: "notice", label: "공지사항", path: "/board/notice" },
  { id: "free", label: "자유게시판", path: "/board/free" },
  { id: "qna", label: "사내 Q&A", path: "/board/qna" },
];

export const BOARD_POSTS = [
  {
    id: "B-2024-001",
    category: "notice",
    title: "2024년 하반기 전사 워크숍 일정 안내",
    content: "안녕하세요. 2024년 하반기 전사 워크숍 일정을 안내드립니다. 일시: 2024년 9월 27일(금) 오전 9시 ~ 오후 6시, 장소: 제주 컨벤션센터. 참석 확인 부탁드립니다. 세부 일정은 첨부 파일을 참고해 주세요.",
    author: TEAM_MEMBERS[0],
    createdAt: "2024-07-10",
    views: 124,
    likes: 18,
    comments: 7,
    isPinned: true,
    tags: ["공지", "워크숍"],
  },
  {
    id: "B-2024-002",
    category: "notice",
    title: "사내 보안 정책 개정 안내 (2024 v3.1)",
    content: "IT 보안팀입니다. 사내 보안 정책이 개정되었습니다. 주요 변경 사항: 비밀번호 정책 강화(90일 주기 변경 → 60일), VPN 필수 사용 범위 확대, 외부 USB 사용 제한. 7월 15일부터 적용되오니 필독 바랍니다.",
    author: TEAM_MEMBERS[2],
    createdAt: "2024-07-09",
    views: 89,
    likes: 5,
    comments: 3,
    isPinned: true,
    tags: ["공지", "보안"],
  },
  {
    id: "B-2024-003",
    category: "free",
    title: "오늘 점심 추천! 회사 근처 새로 생긴 한식당 후기 🍚",
    content: "어제 퇴근 후 회사 근처에 새로 생긴 한식당을 다녀왔는데요, 정말 맛있었어요! 된장찌개와 불고기 정식이 메인인데 1인분에 9,000원으로 가성비도 최고입니다. 점심시간에 같이 가실 분 계신가요?",
    author: TEAM_MEMBERS[3],
    createdAt: "2024-07-11",
    views: 56,
    likes: 14,
    comments: 9,
    isPinned: false,
    tags: ["맛집", "점심"],
  },
  {
    id: "B-2024-004",
    category: "free",
    title: "2분기 목표 초과 달성 축하합니다! 🎉",
    content: "팀원 여러분, 이번 2분기에 목표 대비 112% 달성이라는 놀라운 성과를 이루었습니다. 모두의 노력 덕분입니다. 다음 주 금요일 저녁 팀 회식을 진행할 예정이니 일정 참고 부탁드립니다!",
    author: TEAM_MEMBERS[1],
    createdAt: "2024-07-10",
    views: 73,
    likes: 22,
    comments: 11,
    isPinned: false,
    tags: ["성과", "팀빌딩"],
  },
  {
    id: "B-2024-005",
    category: "qna",
    title: "재택근무 중 장비 비용 지원은 어떻게 신청하나요?",
    content: "안녕하세요. 최근 재택근무 정책이 확대되었다고 들었는데, 외부 모니터나 키보드 같은 장비 지원 신청을 어디서 할 수 있는지 궁금합니다. HR팀에 문의해야 하나요? 아니면 사내 시스템에서 직접 신청이 가능한가요?",
    author: TEAM_MEMBERS[4],
    createdAt: "2024-07-08",
    views: 41,
    likes: 3,
    comments: 4,
    isPinned: false,
    tags: ["HR", "재택근무"],
  },
  {
    id: "B-2024-006",
    category: "qna",
    title: "연차 신청 기한이 어떻게 되나요?",
    content: "연차 사용 시 몇 일 전에 신청해야 하는지 궁금합니다. 급하게 써야 할 경우가 생겼는데 당일 신청도 가능한지, 그리고 승인 절차가 어떻게 되는지 알려주시면 감사하겠습니다.",
    author: TEAM_MEMBERS[3],
    createdAt: "2024-07-07",
    views: 38,
    likes: 2,
    comments: 2,
    isPinned: false,
    tags: ["HR", "연차"],
  },
  {
    id: "B-2024-007",
    category: "free",
    title: "새 디자인 시스템 문서 공개! 다들 한 번씩 읽어봐요 📘",
    content: "안녕하세요 디자인팀 Sofia입니다. 오늘 새 디자인 시스템 v2.0 문서가 사내 Wiki에 공개되었습니다. 컴포넌트 토큰, 색상 팔레트, 타이포그래피 가이드가 모두 업데이트되었으니 개발팀에서도 한 번씩 살펴봐 주시면 좋겠어요!",
    author: TEAM_MEMBERS[4],
    createdAt: "2024-07-06",
    views: 92,
    likes: 15,
    comments: 6,
    isPinned: false,
    tags: ["디자인", "문서"],
  },
  {
    id: "B-2024-008",
    category: "notice",
    title: "7월 정기 시스템 점검 안내 (7/14 일요일 오전 2~4시)",
    content: "IT 인프라팀입니다. 7월 14일(일) 오전 2시부터 4시까지 정기 시스템 점검이 진행됩니다. 해당 시간 동안 WorkSync 서비스 전체가 일시 중단되오니 업무에 참고하시기 바랍니다.",
    author: TEAM_MEMBERS[2],
    createdAt: "2024-07-05",
    views: 67,
    likes: 4,
    comments: 1,
    isPinned: false,
    tags: ["공지", "점검"],
  },
  {
    id: "B-2024-009",
    category: "free",
    title: "개발팀 스터디 모임 참여자 모집합니다",
    content: "매주 화요일 저녁 7시에 진행되는 기술 스터디 모임에 참여하실 분을 모집합니다. 이번 달 주제는 React 19 새로운 기능입니다. 관심 있으신 분은 댓글 남겨주세요!",
    author: TEAM_MEMBERS[3],
    createdAt: "2024-07-04",
    views: 45,
    likes: 8,
    comments: 5,
    isPinned: false,
    tags: ["스터디", "개발"],
  },
  {
    id: "B-2024-010",
    category: "dept",
    title: "디자인팀 8월 UI 트렌드 공유회 안내",
    content: "8월 첫째 주 목요일에 최신 UI/UX 트렌드 공유회를 진행합니다. 2024년 상반기 디자인 트렌드 분석과 하반기 전망을 다룰 예정입니다.",
    author: TEAM_MEMBERS[4],
    createdAt: "2024-07-03",
    views: 32,
    likes: 6,
    comments: 2,
    isPinned: false,
    tags: ["디자인", "세미나"],
  },
  {
    id: "B-2024-011",
    category: "free",
    title: "회사 근처 주차장 정보 공유합니다",
    content: "회사 근처에 월 정기권 가능한 주차장 찾으시는 분들을 위해 정보 공유합니다. 도보 5분 거리에 할인 가능한 곳 있어요.",
    author: TEAM_MEMBERS[2],
    createdAt: "2024-07-02",
    views: 28,
    likes: 4,
    comments: 3,
    isPinned: false,
    tags: ["정보", "주차"],
  },
  {
    id: "B-2024-012",
    category: "qna",
    title: "경조사 휴가 신청 절차 문의드립니다",
    content: "경조사 휴가를 신청하려고 하는데 필요한 서류와 절차가 어떻게 되나요? HR 시스템에서 바로 신청 가능한가요?",
    author: TEAM_MEMBERS[1],
    createdAt: "2024-07-01",
    views: 22,
    likes: 1,
    comments: 2,
    isPinned: false,
    tags: ["HR", "휴가"],
  },
  {
    id: "B-2024-013",
    category: "free",
    title: "점심시간 탁구 같이 치실 분 구합니다",
    content: "매일 점심시간 12시 30분에 1층 휴게실에서 탁구 치고 있습니다. 실력 무관하니 편하게 오세요!",
    author: TEAM_MEMBERS[3],
    createdAt: "2024-06-30",
    views: 38,
    likes: 7,
    comments: 4,
    isPinned: false,
    tags: ["취미", "운동"],
  },
  {
    id: "B-2024-014",
    category: "dept",
    title: "제품팀 7월 월간 회의 안내",
    content: "7월 월간 회의는 7월 20일 오후 3시에 진행됩니다. 각 팀별 진행 상황 공유 및 다음 달 계획 논의 예정입니다.",
    author: TEAM_MEMBERS[1],
    createdAt: "2024-06-29",
    views: 42,
    likes: 3,
    comments: 1,
    isPinned: false,
    tags: ["회의", "제품"],
  },
  {
    id: "B-2024-015",
    category: "free",
    title: "커피 머신 사용법 안내",
    content: "5층 휴게실에 새로 들어온 커피 머신 사용법을 안내드립니다. 아메리카노, 라떼, 카푸치노 모두 가능합니다!",
    author: TEAM_MEMBERS[4],
    createdAt: "2024-06-28",
    views: 55,
    likes: 12,
    comments: 8,
    isPinned: false,
    tags: ["편의시설", "커피"],
  },
  {
    id: "B-2024-016",
    category: "qna",
    title: "야근 식대 지원 기준이 궁금합니다",
    content: "야근 시 식대 지원 기준이 어떻게 되나요? 몇 시 이후부터 인정되는지 알고 싶습니다.",
    author: TEAM_MEMBERS[2],
    createdAt: "2024-06-27",
    views: 31,
    likes: 2,
    comments: 3,
    isPinned: false,
    tags: ["HR", "복리후생"],
  },
  {
    id: "B-2024-017",
    category: "free",
    title: "업무용 노트북 추천 부탁드립니다",
    content: "개인 노트북을 새로 구매하려고 하는데 개발 업무용으로 좋은 제품 추천 부탁드립니다. 예산은 200만원 정도입니다.",
    author: TEAM_MEMBERS[3],
    createdAt: "2024-06-26",
    views: 48,
    likes: 5,
    comments: 11,
    isPinned: false,
    tags: ["질문", "장비"],
  },
  {
    id: "B-2024-018",
    category: "dept",
    title: "개발팀 코드 리뷰 가이드라인 업데이트",
    content: "개발팀 코드 리뷰 가이드라인이 업데이트되었습니다. 주요 변경사항은 Wiki에 정리되어 있으니 확인 부탁드립니다.",
    author: TEAM_MEMBERS[2],
    createdAt: "2024-06-25",
    views: 52,
    likes: 9,
    comments: 4,
    isPinned: false,
    tags: ["개발", "가이드"],
  },
  {
    id: "B-2024-019",
    category: "free",
    title: "사내 동호회 활동 안내",
    content: "현재 운영 중인 사내 동호회는 축구, 등산, 독서, 사진 동호회가 있습니다. 관심 있으신 분은 각 동호회 리더에게 연락주세요!",
    author: TEAM_MEMBERS[1],
    createdAt: "2024-06-24",
    views: 64,
    likes: 14,
    comments: 7,
    isPinned: false,
    tags: ["동호회", "취미"],
  },
  {
    id: "B-2024-020",
    category: "qna",
    title: "건강검진 일정 확인 문의",
    content: "올해 정기 건강검진 일정이 언제인가요? 작년에는 9월에 진행했던 것 같은데 올해도 비슷한 시기인가요?",
    author: TEAM_MEMBERS[4],
    createdAt: "2024-06-23",
    views: 36,
    likes: 3,
    comments: 2,
    isPinned: false,
    tags: ["HR", "건강"],
  },
];

export const NOTIFICATIONS = [
  { id: 1, type: "approval", text: "3분기 예산 요청 결재가 필요합니다", time: "5분 전", read: false, actor: TEAM_MEMBERS[1] },
  { id: 2, type: "mention", text: "Aisha가 업무 T-098에서 나를 멘션했습니다", time: "30분 전", read: false, actor: TEAM_MEMBERS[2] },
  { id: 3, type: "message", text: "Ryan Chen이 메시지를 보냈습니다", time: "1시간 전", read: true, actor: TEAM_MEMBERS[1] },
  { id: 4, type: "task", text: "'인증 토큰 버그' 업무가 검토 중으로 이동되었습니다", time: "2시간 전", read: true, actor: TEAM_MEMBERS[3] },
  { id: 5, type: "system", text: "일요일 오전 2시 시스템 점검이 예정되어 있습니다", time: "1일 전", read: true, actor: null },
  { id: 6, type: "approval", text: "재택근무 정책 개정안이 승인되었습니다", time: "1일 전", read: true, actor: TEAM_MEMBERS[0] },
  { id: 7, type: "mention", text: "Sofia가 디자인 검토 요청 댓글에서 멘션했습니다", time: "2일 전", read: true, actor: TEAM_MEMBERS[4] },
  { id: 8, type: "task", text: "스프린트 7 마감일이 3일 남았습니다", time: "2일 전", read: true, actor: null },
];

export const DOCUMENTS = [
  {
    id: "D-001", title: "2024 3분기 개발팀 기술 스펙 문서", dept: "개발팀", folder: "dept",
    uploader: TEAM_MEMBERS[2], uploadedAt: "2024-07-10", size: "2.4 MB", type: "pdf",
    downloads: 18, isShared: true, tags: ["기술문서", "스펙"],
  },
  {
    id: "D-002", title: "WorkSync 2.0 디자인 목업 v3", dept: "디자인팀", folder: "dept",
    uploader: TEAM_MEMBERS[4], uploadedAt: "2024-07-09", size: "8.1 MB", type: "fig",
    downloads: 12, isShared: true, tags: ["디자인", "목업"],
  },
  {
    id: "D-003", title: "스프린트 7 백로그 및 일정", dept: "제품팀", folder: "dept",
    uploader: TEAM_MEMBERS[1], uploadedAt: "2024-07-08", size: "1.2 MB", type: "xlsx",
    downloads: 25, isShared: true, tags: ["스프린트", "일정"],
  },
  {
    id: "D-004", title: "전사 복리후생 안내 2024", dept: "경영진", folder: "dept",
    uploader: TEAM_MEMBERS[0], uploadedAt: "2024-07-05", size: "0.9 MB", type: "pdf",
    downloads: 54, isShared: true, tags: ["HR", "복리후생"],
  },
  {
    id: "D-005", title: "사내 온보딩 가이드 v2.1", dept: "공용", folder: "shared",
    uploader: TEAM_MEMBERS[0], uploadedAt: "2024-07-03", size: "3.5 MB", type: "pdf",
    downloads: 87, isShared: true, tags: ["온보딩", "가이드"],
  },
  {
    id: "D-006", title: "회의실 예약 규정 및 사용 안내", dept: "공용", folder: "shared",
    uploader: TEAM_MEMBERS[1], uploadedAt: "2024-07-01", size: "0.4 MB", type: "docx",
    downloads: 33, isShared: true, tags: ["총무", "안내"],
  },
  {
    id: "D-007", title: "API 엔드포인트 통합 테스트 결과", dept: "개발팀", folder: "personal",
    uploader: TEAM_MEMBERS[2], uploadedAt: "2024-07-11", size: "1.7 MB", type: "xlsx",
    downloads: 3, isShared: false, tags: ["테스트", "API"],
  },
  {
    id: "D-008", title: "개인 업무 노트 - 7월", dept: "개발팀", folder: "personal",
    uploader: TEAM_MEMBERS[3], uploadedAt: "2024-07-11", size: "0.2 MB", type: "docx",
    downloads: 0, isShared: false, tags: ["개인", "메모"],
  },
];